// packages/ui/theme/generate.ts
// Writes metrics.ts and type.ts from figma-tokens.json, a dump of the Ivy Ai Concepts file's variables ("Ivy · metrics"),
// paint styles ("Colour / …") and text styles. Names are Figma's, character for character, so a re-dump diffs cleanly
// against the design. Refresh the JSON from Figma, then: npm run tokens -w @ivywolf/ui

import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

type Tokens = {
  variables: Record<string, { value: number; frameOnly?: boolean }>
  paints: Record<string, string>
  textStyles: Record<string, { size: number; weight: number; lineHeight: number | null; letterSpacing: number; colour?: string; frameOnly?: boolean }>
}
const dir = __dirname
const t = JSON.parse(readFileSync(join(dir, 'figma-tokens.json'), 'utf8')) as Tokens
const HEAD = (from: string) => `// GENERATED by packages/ui/theme/generate.ts from figma-tokens.json (${from}). Don't edit by hand.\n`
const key = (k: string) => (/^[A-Za-z_]\w*$/.test(k) ? k : `'${k}'`)

// "space/margin" → space.margin; groups in the order Figma lists them.
const groups = new Map<string, string[]>()
for (const [name, { value, frameOnly }] of Object.entries(t.variables)) {
  const [group, leaf] = name.split('/')
  if (!groups.has(group)) groups.set(group, [])
  groups.get(group)!.push(`  ${key(leaf)}: ${value},${frameOnly ? ' // frame only: not bound on a screen yet' : ''}`)
}
// "Colour / Ink" → colour.Ink
const paints = Object.entries(t.paints).map(([name, hex]) => `  ${key(name.split(' / ')[1])}: '${hex}',`)

writeFileSync(
  join(dir, 'metrics.ts'),
  HEAD('Figma collection "Ivy · metrics" + paint styles "Colour / …"') +
    [...groups].map(([g, rows]) => `export const ${g} = {\n${rows.join('\n')}\n} as const\n`).join('\n') +
    `\nexport const colour = {\n${paints.join('\n')}\n} as const\n`
)

// SF Pro is the iOS system font: no fontFamily. Figma's variable weights map to iOS's: 590 semibold, 510 medium.
const weight = (w: number) => String(w >= 650 ? 700 : w >= 560 ? 600 : w >= 460 ? 500 : 400)
const styles = Object.entries(t.textStyles).map(([name, s]) => {
  const colour = s.colour ? `colour.${s.colour.split(' / ')[1]}` : 'colour.Ink'
  const lh = s.lineHeight === null ? '' : ` lineHeight: ${s.lineHeight},`
  return `  '${name}': { fontSize: ${s.size}, fontWeight: '${weight(s.weight)}',${lh} letterSpacing: ${s.letterSpacing}, color: ${colour} },${s.frameOnly ? ' // frame only: not bound on a screen yet' : ''}`
})
writeFileSync(
  join(dir, 'type.ts'),
  HEAD('Figma text styles') +
    `import type { TextStyle } from 'react-native'\nimport { colour } from './metrics'\n\n` +
    `export const type = {\n${styles.join('\n')}\n} as const satisfies Record<string, TextStyle>\n\nexport type TypeName = keyof typeof type\n`
)
console.log('wrote metrics.ts, type.ts')
