// GENERATED by packages/ui/theme/generate.ts from figma-tokens.json (Figma collection "Ivy · metrics" + paint styles "Colour / …"). Don't edit by hand.
export const space = {
  margin: 12, // frame only: not bound on a screen yet
  gutter: 8, // frame only: not bound on a screen yet
  stack: 16, // frame only: not bound on a screen yet
  section: 28, // frame only: not bound on a screen yet
} as const

export const size = {
  'tile-w': 181,
  thumb: 110,
  pin: 30,
  'lime-dot': 36,
  icon: 28, // frame only: not bound on a screen yet
  tap: 44, // frame only: not bound on a screen yet
  nav: 56, // frame only: not bound on a screen yet
  'bar-h': 72,
} as const

export const radius = {
  tile: 20,
  thumb: 18,
  chip: 14, // frame only: not bound on a screen yet
  button: 26, // frame only: not bound on a screen yet
  bar: 28,
} as const

export const colour = {
  Ink: '#1D1D1F',
  Grey: '#6E6E73',
  Lime: '#D8F27A',
  Chip: '#F0F0F0',
  Surface: '#FFFFFF',
  Shimmer: '#E5E5E8',
} as const
