// GENERATED by packages/ui/theme/generate.ts from figma-tokens.json (Figma text styles). Don't edit by hand.
import type { TextStyle } from 'react-native'
import { colour } from './metrics'

export const type = {
  'Title / Screen': { fontSize: 34, fontWeight: '700', lineHeight: 36, letterSpacing: -0.6, color: colour.Ink },
  'Title / Section': { fontSize: 22, fontWeight: '700', lineHeight: 28, letterSpacing: -0.4, color: colour.Ink },
  'Heading / Small': { fontSize: 18, fontWeight: '600', lineHeight: 22, letterSpacing: -0.2, color: colour.Ink },
  'Heading / Card': { fontSize: 17, fontWeight: '600', lineHeight: 24, letterSpacing: -0.3, color: colour.Ink },
  'Body / Large': { fontSize: 17, fontWeight: '400', lineHeight: 24, letterSpacing: 0, color: colour.Ink },
  'Body': { fontSize: 15, fontWeight: '400', lineHeight: 21, letterSpacing: 0, color: colour.Ink },
  'Body / Medium': { fontSize: 15, fontWeight: '500', lineHeight: 18, letterSpacing: 0, color: colour.Ink },
  'Body / Small': { fontSize: 13, fontWeight: '400', lineHeight: 18, letterSpacing: 0, color: colour.Ink },
  'Caption': { fontSize: 13, fontWeight: '400', letterSpacing: 0, color: colour.Grey }, // frame only: not bound on a screen yet
  'Label / Overline': { fontSize: 11, fontWeight: '600', lineHeight: 14, letterSpacing: 1.2, color: colour.Ink },
  'Label / Tab': { fontSize: 12, fontWeight: '500', lineHeight: 13, letterSpacing: 0.2, color: colour.Ink },
  'Label / Pill': { fontSize: 11, fontWeight: '500', lineHeight: 12, letterSpacing: 0.5, color: colour.Ink },
} as const satisfies Record<string, TextStyle>

export type TypeName = keyof typeof type
