-- Rolled-back test for 0029 (write, test in a rolled-back transaction, dry-run, push).
--
--   node scripts/build-sql-test.mjs 0029 && supabase db query --linked -f scripts/test-0029.sql

-- Generated by scripts/build-sql-test.mjs from test-0029.head.sql, 0029, test-0029.body.sql.
begin;
-- More ideas (Job G §3.3–3.4): what she does to a suggestion, as one call each — the status change and its
-- suggestion_signals row together, only on her own, only from 'shown' (a dismissed or hidden suggestion never comes
-- back, and a pinned one can't be dismissed after). Style signals are written by the bridge (Job G step 6), not here.
--
--   act_on_suggestion(id, 'hide')     long-press on a tile — a negative signal, no UI
--   act_on_suggestion(id, 'dismiss')  "Not for me" on the open screen
--   pin_suggestion(id)                "+ Pin to <project>" — a later migration: it also makes the card

create function act_on_suggestion(p_suggestion uuid, p_signal text)
returns boolean
language plpgsql security definer set search_path = public as $$
declare
  me text := auth.jwt() ->> 'sub';
  status_to text := case p_signal when 'hide' then 'hidden' when 'dismiss' then 'dismissed' end;
  n int;
begin
  if me is null then raise exception 'act_on_suggestion: no signed-in creator'; end if;
  if status_to is null then raise exception 'act_on_suggestion: % is not hide or dismiss', p_signal; end if;
  update suggestions set status = status_to, acted_at = now()
   where id = p_suggestion and creator_id = me and status = 'shown';
  get diagnostics n = row_count;
  if n = 0 then return false; end if;  -- not hers, gone, or already acted on: nothing to log
  insert into suggestion_signals (creator_id, suggestion_id, signal) values (me, p_suggestion, p_signal);
  return true;
end;
$$;
revoke execute on function act_on_suggestion(uuid, text) from public, anon;
grant execute on function act_on_suggestion(uuid, text) to authenticated;

create temp table r(n serial, check_name text, ok boolean, detail text) on commit drop;
grant all on r to authenticated; grant all on r_n_seq to authenticated;

do $$
declare me text := 'user_3JfFAEHAdkvURqPjYDQ4BkVd2rb'; other text := 'user_3JfYR4D8eJVCL3yieXStYYoqwaH'; a uuid; b uuid; o uuid;
begin
  insert into suggestions (creator_id, field, source, title, rank) values (me, 'format', 'youtube', 'A', 1) returning id into a;
  insert into suggestions (creator_id, field, source, title, rank) values (me, 'sound', 'tiktok', 'B', 2) returning id into b;
  insert into suggestions (creator_id, field, source, title, rank) values (other, 'sound', 'tiktok', 'O', 1) returning id into o;
  perform set_config('t.a', a::text, true); perform set_config('t.b', b::text, true); perform set_config('t.o', o::text, true);
end $$;

select set_config('request.jwt.claims', '{"sub":"user_3JfFAEHAdkvURqPjYDQ4BkVd2rb","role":"authenticated"}', true);
set local role authenticated;
do $$
declare ok1 boolean; ok2 boolean; st text; n int;
begin
  ok1 := act_on_suggestion(current_setting('t.a')::uuid, 'hide');
  ok2 := act_on_suggestion(current_setting('t.a')::uuid, 'hide');
  select status into st from suggestions where id = current_setting('t.a')::uuid;
  select count(*) into n from suggestion_signals where suggestion_id = current_setting('t.a')::uuid and signal = 'hide';
  insert into r values (default, 'hide: hidden, one signal; a second hide does nothing', ok1 and not ok2 and st = 'hidden' and n = 1, format('%s %s %s %s', ok1, ok2, st, n));

  ok1 := act_on_suggestion(current_setting('t.b')::uuid, 'dismiss');
  select status into st from suggestions where id = current_setting('t.b')::uuid;
  insert into r values (default, 'dismiss: dismissed', ok1 and st = 'dismissed', st);
  ok1 := act_on_suggestion(current_setting('t.b')::uuid, 'hide');
  insert into r values (default, 'a dismissed suggestion can''t be acted on again', not ok1, ok1::text);

  ok1 := act_on_suggestion(current_setting('t.o')::uuid, 'dismiss');
  insert into r values (default, 'another creator''s suggestion is untouched', not ok1, ok1::text);

  begin
    perform act_on_suggestion(current_setting('t.a')::uuid, 'pin');
    insert into r values (default, 'pin isn''t a plain status change', false, 'ran');
  exception when raise_exception then
    insert into r values (default, 'pin isn''t a plain status change', true, sqlerrm);
  end;

  select count(*) into n from style_signals where creator_id = 'user_3JfFAEHAdkvURqPjYDQ4BkVd2rb' and created_at >= now();
  insert into r values (default, 'no style signals yet (the bridge is step 6)', n = 0, n::text);
end $$;
reset role;
do $$
declare st text;
begin
  select status into st from suggestions where id = current_setting('t.o')::uuid;
  insert into r values (default, '…still shown', st = 'shown', st);
end $$;

select n, case when ok then 'pass' else 'FAIL' end as result, check_name, detail from r order by n;
rollback;
