-- Rolled-back test for 0031 (write, test in a rolled-back transaction, dry-run, push).
--
--   node scripts/build-sql-test.mjs 0031 && supabase db query --linked -f scripts/test-0031.sql

-- Generated by scripts/build-sql-test.mjs from test-0031.head.sql, 0031, test-0031.body.sql.
begin;
-- A pinned own-graph suggestion keeps source 'graph' (Job G decision, 29 Sep): it still sits on the recording and
-- moment its why line cites, but the provenance is the signal — a card that came from a suggestion must never look
-- like one she rambled. 0030 made it 'voice'; nothing was pinned from the graph before this ran.
--
--   cards.source  + 'graph'. A graph card must still have its recording (0028's rule names only youtube / tiktok /
--                 pinterest as recording-less).
--   pin_suggestion  the card's source is the suggestion's, always.

alter table cards drop constraint cards_source_check;
alter table cards add constraint cards_source_check
  check (source in ('voice', 'import', 'muse', 'youtube', 'tiktok', 'pinterest', 'graph'));

create or replace function pin_suggestion(p_suggestion uuid)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  me text := auth.jwt() ->> 'sub';
  s suggestions%rowtype;
  card uuid;
  rec uuid;
  ms int := 0;
begin
  if me is null then raise exception 'pin_suggestion: no signed-in creator'; end if;
  select * into s from suggestions where id = p_suggestion and creator_id = me for update;
  if not found then raise exception 'pin_suggestion: no such suggestion'; end if;

  if s.status = 'pinned' then
    select id into card from cards where source_suggestion_id = s.id and creator_id = me order by created_at limit 1;
    return card;
  end if;
  if s.status <> 'shown' then raise exception 'pin_suggestion: this suggestion was %', s.status; end if;

  if s.source = 'graph' then
    rec := coalesce(s.why_recording_id, (select recording_id from cards where id = s.near_card_id));
    ms := coalesce(s.why_ms, (select play_from_ms from cards where id = s.near_card_id), 0);
    if rec is null then raise exception 'pin_suggestion: a graph suggestion needs the recording it came from'; end if;
  end if;

  insert into cards (creator_id, recording_id, project_id, title, gist, play_from_ms, confidence,
                     source, source_url, source_suggestion_id, frame_url, frame_status, frame_at)
  values (me, rec, s.project_id, s.title, s.title, ms, 1,
          s.source, s.source_url, s.id,
          s.frame_url, case when s.frame_url is null then 'none' else 'done' end,
          case when s.frame_url is null then null else now() end)
  returning id into card;

  if s.thread_id is not null then
    insert into thread_cards (thread_id, card_id) values (s.thread_id, card) on conflict do nothing;
  end if;
  update suggestions set status = 'pinned', acted_at = now() where id = s.id;
  insert into suggestion_signals (creator_id, suggestion_id, signal) values (me, s.id, 'pin');
  return card;
end;
$$;

create temp table r(n serial, check_name text, ok boolean, detail text) on commit drop;
grant all on r to authenticated; grant all on r_n_seq to authenticated;

do $$
declare me text := 'user_3JfFAEHAdkvURqPjYDQ4BkVd2rb'; rec uuid; g uuid; yt uuid;
begin
  insert into recordings (creator_id, source, storage_path) values (me, 'phone', 'test/0031') returning id into rec;
  insert into suggestions (creator_id, field, source, title, why, why_recording_id, why_ms, rank)
    values (me, 'graph', 'graph', 'Told from the ground', 'You keep coming back', rec, 31000, 1) returning id into g;
  insert into suggestions (creator_id, field, source, source_url, title, rank)
    values (me, 'format', 'youtube', 'https://example.com/v', 'Open on the box', 2) returning id into yt;
  perform set_config('t.g', g::text, true); perform set_config('t.yt', yt::text, true); perform set_config('t.rec', rec::text, true);
  begin
    insert into cards (creator_id, title, gist, play_from_ms, confidence, source) values (me, 'x', 'x', 0, 1, 'graph');
    insert into r values (default, 'a graph card still needs its recording', false, 'inserted');
  exception when check_violation then
    insert into r values (default, 'a graph card still needs its recording', true, sqlerrm);
  end;
end $$;

select set_config('request.jwt.claims', '{"sub":"user_3JfFAEHAdkvURqPjYDQ4BkVd2rb","role":"authenticated"}', true);
set local role authenticated;
do $$
declare c uuid; src text; rec uuid; ms int;
begin
  c := pin_suggestion(current_setting('t.g')::uuid);
  select source, recording_id, play_from_ms into src, rec, ms from cards where id = c;
  insert into r values (default, 'an own-graph pin keeps source graph, on its recording and moment',
    src = 'graph' and rec = current_setting('t.rec')::uuid and ms = 31000, format('%s %s %s', src, rec, ms));
  c := pin_suggestion(current_setting('t.yt')::uuid);
  select source into src from cards where id = c;
  insert into r values (default, 'a youtube pin is still youtube', src = 'youtube', src);
end $$;
reset role;

select n, case when ok then 'pass' else 'FAIL' end as result, check_name, detail from r order by n;
rollback;
