-- Rolled-back test for 0025 (write, test in a rolled-back transaction, dry-run, push).
-- Applies 0024 (0025 references creator_api_keys) and 0025 inside the transaction, and rolls everything back.
--
--   node scripts/build-sql-test.mjs 0025 && supabase db query --linked -f scripts/test-0025.sql

-- Generated by scripts/build-sql-test.mjs from test-0025.head.sql, 0024 + 0025, test-0025.body.sql.
begin;
-- The Muse connector's keys (Job F §4). A creator makes a key in Connect your Muse, pastes it into Muse as a custom
-- connector, and Muse calls /mcp with `Authorization: Bearer iv_…`. Least privilege (§2 rule 4): each key carries its
-- scopes, and there are two — ideas:read ("Let Muse read your ideas") and ideas:capture ("Let Muse add ideas to Ivy").
--
-- Replaces api_keys (0004), which had no scopes: a key there could do anything the MCP server offered. Its rows are
-- copied here as read-only keys; api_keys stays until a later migration drops it (nothing reads it after this job).
--
-- Only the SHA-256 hash is stored (apps/web/lib/mcp/auth.ts); the raw key is shown once. Revoked, never deleted,
-- so the audit trail survives. The creator reads her keys' labels and dates but never the hash, and may change
-- only the label and revoked_at — scopes are fixed at creation, so widening a key means making a new one.

create table creator_api_keys (
  id uuid primary key default gen_random_uuid(),
  creator_id text not null references creators(id) on delete cascade,
  hash text not null unique,
  scopes text[] not null check (cardinality(scopes) > 0 and scopes <@ array['ideas:read', 'ideas:capture']),
  label text not null default 'Muse' check (length(btrim(label)) between 1 and 60),
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);
create index on creator_api_keys (creator_id, created_at desc);

alter table creator_api_keys enable row level security;
create policy "own api keys: read" on creator_api_keys for select using (creator_id = (auth.jwt() ->> 'sub'));
create policy "own api keys: create" on creator_api_keys for insert with check (creator_id = (auth.jwt() ->> 'sub'));
create policy "own api keys: revoke" on creator_api_keys for update
  using (creator_id = (auth.jwt() ->> 'sub'))
  with check (creator_id = (auth.jwt() ->> 'sub'));

-- Column grants: RLS picks the rows, these pick the columns (as recordings, 0006). No delete grant at all.
revoke all on creator_api_keys from anon, authenticated;
grant select (id, creator_id, scopes, label, created_at, last_used_at, revoked_at) on creator_api_keys to authenticated;
grant insert (creator_id, hash, scopes, label) on creator_api_keys to authenticated;
grant update (label, revoked_at) on creator_api_keys to authenticated;

-- A revoked key stays revoked.
create function keep_key_revoked() returns trigger
language plpgsql
as $$
begin
  if old.revoked_at is not null and new.revoked_at is distinct from old.revoked_at then
    raise exception 'a revoked key cannot be restored' using errcode = '42501';
  end if;
  return new;
end;
$$;
create trigger creator_api_keys_keep_revoked before update of revoked_at on creator_api_keys
  for each row execute function keep_key_revoked();

insert into creator_api_keys (creator_id, hash, scopes, label, created_at, last_used_at, revoked_at)
select creator_id, key_hash, array['ideas:read'], left(label, 60), created_at, last_used_at, revoked_at from api_keys
on conflict (hash) do nothing;

-- The Muse connector's own tables (Job F §2 rules 6 and 7).
--
-- agent_calls — one row per MCP tool call, kept apart from everything the app logs (source 'muse'), so we can see
-- what creators ask their Muse: the free "questions people ask" study (§7 — the top five become Home's earned
-- in-feed blocks). What's kept is the shape of the ask, not her words: the tool, its non-text parameters (since,
-- limit, status, min_returns…) and how it went. A search query or a captured idea is never copied here — the idea
-- already lives on its recording, and deleting that recording (0007) must leave nothing of it behind.
-- Service role only: RLS on, no policies.

create table agent_calls (
  id uuid primary key default gen_random_uuid(),
  creator_id text not null references creators(id) on delete cascade,
  key_id uuid references creator_api_keys(id) on delete set null,
  source text not null default 'muse',           -- every key today is made in Connect your Muse
  tool text not null,
  params jsonb not null default '{}',            -- non-text arguments only (apps/web/lib/mcp/tools.ts)
  ok boolean,                                    -- null while the call runs
  error text,                                    -- the sentence she was shown, or 'internal'
  latency_ms int,
  created_at timestamptz not null default now()
);
create index agent_calls_creator_idx on agent_calls (creator_id, created_at desc);
create index agent_calls_tool_idx on agent_calls (tool, created_at desc);

alter table agent_calls enable row level security;

create temp table r(n serial, check_name text, ok boolean, detail text) on commit drop;
grant all on r to authenticated; grant all on r_n_seq to authenticated;

do $$
declare me text := 'user_3JfFAEHAdkvURqPjYDQ4BkVd2rb'; c uuid;
begin
  insert into agent_calls (creator_id, tool, params) values (me, 'list_ideas', '{"since":"2026-09-21","limit":20}') returning id into c;
  perform set_config('t.call', c::text, true);
  update agent_calls set ok = true, latency_ms = 42 where id = c;
  insert into r (check_name, ok, detail)
    select 'a call is logged as muse', source = 'muse' and ok and latency_ms = 42, source || ' ' || ok::text from agent_calls where id = c;
end $$;

-- ── She can't read or write the log ───────────────────────────────────────────────────────────────────────────
select set_config('request.jwt.claims', '{"sub":"user_3JfFAEHAdkvURqPjYDQ4BkVd2rb","role":"authenticated"}', true);
set local role authenticated;
do $$
declare n int;
begin
  select count(*) into n from agent_calls;
  insert into r (check_name, ok, detail) values ('she can''t read agent_calls', n = 0, n::text);
  begin
    insert into agent_calls (creator_id, tool) values ('user_3JfFAEHAdkvURqPjYDQ4BkVd2rb', 'list_ideas');
    insert into r (check_name, ok, detail) values ('she can''t write agent_calls', false, 'inserted');
  exception when insufficient_privilege then
    insert into r (check_name, ok, detail) values ('she can''t write agent_calls', true, sqlerrm);
  end;
end $$;
reset role;

select n, case when ok then 'pass' else 'FAIL' end as result, check_name, detail from r order by n;
rollback;
