-- Rolled-back test for 0038 (write, test in a rolled-back transaction, dry-run, push). Job H: directions.
--
--   node scripts/build-sql-test.mjs 0038 && supabase db query --linked -f scripts/test-0038.sql

-- Generated by scripts/build-sql-test.mjs from test-0038.head.sql, 0038, test-0038.body.sql.
begin;
-- 0038 — More ideas, free (Job H): Ivy's directions for a project, and the form profile they follow.
--
-- A direction is a suggestion of kind 'direction' (suggestions, 0028): something her own cards point to that she hasn't
-- said yet — never a rewording of a card — with one cited line of her own words, a form, and a visual_query for its
-- references (looked up live, never stored: packages/pipeline/references). Written by the pipeline (service role);
-- she reads her own (the 0028 policy) and acts through the functions below. Nothing here spends credits.
--
-- Columns the brief names that 0028 already has are reused, not duplicated:
--   cite_recording_id → why_recording_id   (0028 already forgets it when the recording is deleted)
--   cite_ms           → why_ms
--   the cited line    → why
--   project_id, status (extended with new / saved below)
-- New: kind, gist, cite_card_ids, format, visual_query, payload, generated_at, model_version, hearted_at.
-- payload is what the direction's form needs to stand as a card (0033 cards_shape_has_payload): {"board": {hook,
-- beats}} | {"quote": {text, speaker}} | {"diagram": {title, rows}}; a quote's text is her words, verbatim.
--
-- projects.format_profile — rolling counts of the forms she keeps, hearts, pins and dismisses (last 90 days),
-- recomputed by trigger. projects.directions_stale_at marks that something changed (a card landed, a pin, a heart, a
-- link); generation waits until it has been quiet 5 minutes (the debounce) and runs when the project is next opened,
-- or when the last generation is over 24 h old. projects.directions_at is the last generation.

-- ── suggestions → directions ────────────────────────────────────────────────────────────────────────────────────
alter table suggestions
  add column kind text not null default 'suggestion' check (kind in ('suggestion', 'direction')),
  add column gist text,
  add column cite_card_ids uuid[] not null default '{}',
  add column format text check (format in ('photo', 'quote', 'board', 'diagram', 'text', 'video')),
  add column visual_query text,
  add column payload jsonb not null default '{}',
  add column generated_at timestamptz,
  add column model_version text,
  add column hearted_at timestamptz;

alter table suggestions drop constraint suggestions_status_check;
alter table suggestions add constraint suggestions_status_check
  check (status in ('shown', 'pinned', 'dismissed', 'hidden', 'expired', 'new', 'saved'));

-- A direction always carries what makes it hers: a project, a form, at least one cited card and the cited line.
alter table suggestions add constraint suggestions_direction_complete check (
  kind <> 'direction' or (
    project_id is not null and format is not null and why is not null and cardinality(cite_card_ids) >= 1
    and generated_at is not null and model_version is not null
    and status in ('new', 'saved', 'dismissed', 'expired')
  )
);
create index suggestions_directions_idx on suggestions (project_id, status, generated_at desc) where kind = 'direction';

alter table suggestion_signals drop constraint suggestion_signals_signal_check;
alter table suggestion_signals add constraint suggestion_signals_signal_check
  check (signal in ('pin', 'dismiss', 'hide', 'open', 'play_why', 'save', 'heart', 'unheart'));

-- ── cards: a saved direction becomes a card ─────────────────────────────────────────────────────────────────────
alter table cards drop constraint cards_source_check;
alter table cards add constraint cards_source_check
  check (source in ('voice', 'import', 'muse', 'youtube', 'tiktok', 'graph', 'direction'));

-- ── projects: the form profile and the generation clock ─────────────────────────────────────────────────────────
alter table projects
  add column format_profile jsonb not null default '{}',
  add column directions_stale_at timestamptz,
  add column directions_at timestamptz;

-- {"kept": {"board": 3, …}, "hearted": {…}, "pinned": {…}, "dismissed": {…}, "updated_at": "…"} over the last 90 days.
-- kept = cards in the project by form; dismissed = directions she ✕'d, by form.
create or replace function recompute_format_profile(p_project uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update projects p set format_profile = jsonb_build_object(
    'kept',      coalesce((select jsonb_object_agg(f, n) from (select coalesce(shape, 'text') f, count(*) n from cards
                   where project_id = p_project and created_at > now() - interval '90 days' group by 1) x), '{}'),
    'hearted',   coalesce((select jsonb_object_agg(f, n) from (select coalesce(shape, 'text') f, count(*) n from cards
                   where project_id = p_project and hearted_at > now() - interval '90 days' group by 1) x), '{}'),
    'pinned',    coalesce((select jsonb_object_agg(f, n) from (select coalesce(shape, 'text') f, count(*) n from cards
                   where project_id = p_project and pinned_at > now() - interval '90 days' group by 1) x), '{}'),
    'dismissed', coalesce((select jsonb_object_agg(f, n) from (select format f, count(*) n from suggestions
                   where project_id = p_project and kind = 'direction' and status = 'dismissed'
                     and acted_at > now() - interval '90 days' group by 1) x), '{}'),
    'updated_at', now()
  )
  where p.id = p_project;
$$;

-- Cards: a new card, a changed form, a pin or a heart → the profile moves and directions are due.
create or replace function cards_directions_changed()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    if old.project_id is not null then perform recompute_format_profile(old.project_id); end if;
    return old;
  end if;
  if new.project_id is not null then
    perform recompute_format_profile(new.project_id);
    if tg_op = 'INSERT' or new.pinned_at is distinct from old.pinned_at or new.hearted_at is distinct from old.hearted_at
       or new.project_id is distinct from old.project_id then
      update projects set directions_stale_at = now() where id = new.project_id;
    end if;
  end if;
  if tg_op = 'UPDATE' and old.project_id is distinct from new.project_id and old.project_id is not null then
    perform recompute_format_profile(old.project_id);
  end if;
  return new;
end;
$$;

create trigger cards_directions_changed after insert or delete or update of shape, hearted_at, pinned_at, project_id on cards
  for each row execute function cards_directions_changed();

-- Directions: a dismiss feeds the profile.
create or replace function directions_status_changed()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.kind = 'direction' and new.status is distinct from old.status and new.project_id is not null then
    perform recompute_format_profile(new.project_id);
  end if;
  return new;
end;
$$;

create trigger directions_status_changed after update of status on suggestions
  for each row execute function directions_status_changed();

-- Link ideas → both cards' projects are due.
create or replace function card_links_directions_due()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update projects set directions_stale_at = now()
   where id in (select project_id from cards where id in (new.card_a, new.card_b) and project_id is not null);
  return new;
end;
$$;
create trigger card_links_directions_due after insert on card_links
  for each row execute function card_links_directions_due();

-- ── What she does to a direction: one call each, her own only ───────────────────────────────────────────────────

-- Save (+): a real card in the project — her cite carried over (the recording and moment she said it), the form kept
-- with its payload, references dropped (they were never stored). 'video' has no card form yet, so it is kept as a
-- board. A form whose payload is missing stands as text rather than failing (0033 cards_shape_has_payload).
create or replace function save_direction(p_suggestion uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  me text := auth.jwt() ->> 'sub';
  s suggestions%rowtype;
  card uuid;
  form text;
begin
  if me is null then raise exception 'save_direction: no signed-in creator'; end if;
  select * into s from suggestions where id = p_suggestion and creator_id = me and kind = 'direction' for update;
  if not found then raise exception 'save_direction: no such direction'; end if;
  if s.status = 'saved' then
    select id into card from cards where source_suggestion_id = s.id and creator_id = me order by created_at limit 1;
    return card;
  end if;
  if s.status <> 'new' then raise exception 'save_direction: this direction was %', s.status; end if;
  if s.why_recording_id is null then raise exception 'save_direction: a direction needs the recording it cites'; end if;

  form := case when s.format = 'video' then 'board' else s.format end;
  if (form = 'board' and s.payload -> 'board' is null) or (form = 'quote' and s.payload -> 'quote' is null)
     or (form = 'diagram' and s.payload -> 'diagram' is null) then
    form := 'text';
  end if;
  insert into cards (creator_id, recording_id, project_id, title, gist, play_from_ms, confidence, source,
                     source_suggestion_id, shape, shape_set_by, visual_query, quote, diagram, board, frame_status)
  values (me, s.why_recording_id, s.project_id, s.title, coalesce(s.gist, s.title), coalesce(s.why_ms, 0), 1, 'direction',
          s.id, form, 'ivy', s.visual_query,
          case when form = 'quote' then s.payload -> 'quote' end,
          case when form = 'diagram' then s.payload -> 'diagram' end,
          case when form = 'board' then s.payload -> 'board' end,
          'none')
  returning id into card;

  update suggestions set status = 'saved', acted_at = now() where id = s.id;
  insert into suggestion_signals (creator_id, suggestion_id, signal) values (me, s.id, 'save');
  return card;
end;
$$;

-- ✕: dismissed for good; feeds the profile (trigger above) and the avoid-list of the next generation.
create or replace function dismiss_direction(p_suggestion uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare me text := auth.jwt() ->> 'sub';
begin
  if me is null then raise exception 'dismiss_direction: no signed-in creator'; end if;
  update suggestions set status = 'dismissed', acted_at = now()
   where id = p_suggestion and creator_id = me and kind = 'direction' and status = 'new';
  if not found then raise exception 'dismiss_direction: no such new direction'; end if;
  insert into suggestion_signals (creator_id, suggestion_id, signal) values (me, p_suggestion, 'dismiss');
end;
$$;

-- ♥: a favourite, on or off. A positive signal; nothing else changes.
create or replace function heart_direction(p_suggestion uuid, p_on boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare me text := auth.jwt() ->> 'sub';
begin
  if me is null then raise exception 'heart_direction: no signed-in creator'; end if;
  update suggestions set hearted_at = case when p_on then coalesce(hearted_at, now()) end
   where id = p_suggestion and creator_id = me and kind = 'direction';
  if not found then raise exception 'heart_direction: no such direction'; end if;
  insert into suggestion_signals (creator_id, suggestion_id, signal) values (me, p_suggestion, case when p_on then 'heart' else 'unheart' end);
end;
$$;

grant execute on function save_direction(uuid), dismiss_direction(uuid), heart_direction(uuid, boolean) to authenticated;

-- Every existing project starts with its profile.
select recompute_format_profile(id) from projects;

create temp table r(n serial, check_name text, ok boolean, detail text) on commit drop;
grant all on r to authenticated; grant all on r_n_seq to authenticated;

do $$
declare
  me text := 'user_3JfYR4D8eJVCL3yieXStYYoqwaH';
  proj uuid := 'ede3b0af-ae8c-4c53-a6e2-b126d92015dd'; -- Launch video
  c record; d uuid; v uuid; w uuid; n int; prof jsonb;
begin
  select id, recording_id, play_from_ms into c from cards where project_id = proj order by created_at limit 1;
  select format_profile into prof from projects where id = proj;
  insert into r values (default, 'existing projects get a profile', prof ? 'kept' and prof ? 'dismissed', prof::text);

  insert into suggestions (creator_id, project_id, field, source, title, gist, why, why_recording_id, why_ms, rank, kind,
                           cite_card_ids, format, visual_query, status, generated_at, model_version)
  values (me, proj, 'graph', 'graph', 'Test direction', 'gist', 'from Thu 0:31: “x”', c.recording_id, c.play_from_ms, 1,
          'direction', array[c.id], 'board', 'dusk rooftops', 'new', now(), 'direction_v1') returning id into d;
  update suggestions set payload = '{"board": {"hook": "Open on the drop", "beats": ["Run", "Leap", "Hold it up"]}}' where id = d;
  insert into suggestions (creator_id, project_id, field, source, title, why, why_recording_id, rank, kind, cite_card_ids,
                           format, status, generated_at, model_version)
  values (me, proj, 'graph', 'graph', 'Video direction', 'from Thu 0:31: “y”', c.recording_id, 2, 'direction', array[c.id],
          'video', 'new', now(), 'direction_v1') returning id into v;
  insert into r values (default, 'a complete direction is accepted', true, d::text);
  begin
    insert into suggestions (creator_id, project_id, field, source, title, rank, kind, format, status, generated_at, model_version)
    values (me, proj, 'graph', 'graph', 'No cite', 3, 'direction', 'text', 'new', now(), 'direction_v1');
    insert into r values (default, 'a direction without a cited line and card is refused', false, 'inserted');
  exception when check_violation then
    insert into r values (default, 'a direction without a cited line and card is refused', true, sqlerrm);
  end;
  insert into suggestions (creator_id, project_id, field, source, title, why, why_recording_id, rank, kind, cite_card_ids,
                           format, status, generated_at, model_version)
  values (me, proj, 'graph', 'graph', 'Bare video', 'from Thu 0:31: “z”', c.recording_id, 4, 'direction', array[c.id],
          'video', 'new', now(), 'direction_v1') returning id into w;
  perform set_config('t.w', w::text, true);
  perform set_config('t.d', d::text, true);
  perform set_config('t.v', v::text, true);
  perform set_config('t.c', c.id::text, true);
end $$;

select set_config('request.jwt.claims', '{"sub":"user_3JfYR4D8eJVCL3yieXStYYoqwaH","role":"authenticated"}', true);
set local role authenticated;
do $$
declare card uuid; card2 uuid; n int; s text; src text; shp text; rec uuid; prof jsonb; stale timestamptz;
begin
  card := save_direction(current_setting('t.d')::uuid);
  select source, shape, recording_id into src, shp, rec from cards where id = card;
  insert into r values (default, 'Save makes a card: source direction, form and payload kept, cite carried', src = 'direction' and shp = 'board' and rec is not null
    and (select board ->> 'hook' from cards where id = card) = 'Open on the drop', format('%s %s', src, shp));
  select status into s from suggestions where id = current_setting('t.d')::uuid;
  insert into r values (default, 'the direction is saved', s = 'saved', s);
  card2 := save_direction(current_setting('t.d')::uuid);
  insert into r values (default, 'saving twice returns the same card', card2 = card, card2::text);

  card2 := save_direction(current_setting('t.w')::uuid);
  select shape into shp from cards where id = card2;
  insert into r values (default, 'a video with no board payload saves as text, not a failure', shp = 'text', shp);
  perform heart_direction(current_setting('t.v')::uuid, true);
  select count(*) into n from suggestions where id = current_setting('t.v')::uuid and hearted_at is not null;
  insert into r values (default, '♥ marks a favourite', n = 1, n::text);
  perform dismiss_direction(current_setting('t.v')::uuid);
  select status into s from suggestions where id = current_setting('t.v')::uuid;
  insert into r values (default, '✕ dismisses', s = 'dismissed', s);
  begin
    perform save_direction(current_setting('t.v')::uuid);
    insert into r values (default, 'a dismissed direction can''t be saved', false, 'saved');
  exception when others then
    insert into r values (default, 'a dismissed direction can''t be saved', true, sqlerrm);
  end;
end $$;
reset role;

do $$
declare prof jsonb; stale timestamptz; before timestamptz; video_card uuid;
begin
  select format_profile, directions_stale_at into prof, stale from projects where id = 'ede3b0af-ae8c-4c53-a6e2-b126d92015dd';
  insert into r values (default, 'a ✕ feeds the profile (dismissed: video)', (prof -> 'dismissed' ->> 'video')::int >= 1, prof -> 'dismissed' ->> 'video');
  insert into r values (default, 'a saved direction lands as a kept board', (prof -> 'kept' ->> 'board')::int >= 1, prof -> 'kept' ->> 'board');
  insert into r values (default, 'a new card marks directions due', stale > now() - interval '1 minute', stale::text);
  update projects set directions_stale_at = null where id = 'ede3b0af-ae8c-4c53-a6e2-b126d92015dd';
  update cards set hearted_at = now() where id = current_setting('t.c')::uuid;
  select directions_stale_at into stale from projects where id = 'ede3b0af-ae8c-4c53-a6e2-b126d92015dd';
  insert into r values (default, 'a heart marks directions due', stale is not null, coalesce(stale::text, 'null'));
end $$;

select n, case when ok then 'pass' else 'FAIL' end as result, check_name, detail from r order by n;
rollback;
