-- Rolled-back test for 0028 (write, test in a rolled-back transaction, dry-run, push).
--
--   node scripts/build-sql-test.mjs 0028 && supabase db query --linked -f scripts/test-0028.sql

-- Generated by scripts/build-sql-test.mjs from test-0028.head.sql, 0028, test-0028.body.sql.
begin;
-- More ideas (Job G §4): suggestions pushed to a thread, what she did with them, and the style signals they feed.
--
--   suggestions          up to five per thread, shown on a project's More ideas tab (gate: a thread in the project
--                        with return_count >= 3). Seeded from JSON (scripts/seed-suggestions.ts) until Job H's
--                        adapters. Written by the service role; she reads her own. Status changes go through the
--                        pin / dismiss functions (a later migration), never a direct update.
--   suggestion_signals   one row per thing she did to a suggestion: pin, dismiss, hide, open, play_why.
--   style_signals        her taste as events — a suggestion pinned or dismissed here, a take picked in Job D. One
--                        writer: write_style_signal(kind, payload). Not style_packs: those are the summary, these
--                        are what it's summarised from.
--   cards                a pinned suggestion becomes a card: source widens past voice/import, source_url and
--                        source_suggestion_id are new, and such a card has no recording.
--
-- Creator ids are Clerk ids (text), as creators.id. A card reaches its thread through thread_cards.

-- ── suggestions ─────────────────────────────────────────────────────────────────────────────────────────────────
create table suggestions (
  id uuid primary key default gen_random_uuid(),
  creator_id text not null references creators(id) on delete cascade,
  project_id uuid references projects(id) on delete cascade,
  thread_id uuid references threads(id) on delete cascade,
  near_card_id uuid references cards(id) on delete set null,    -- "Near: <title>" on the open screen
  field text not null check (field in ('format', 'sound', 'aesthetic', 'topic', 'graph')),
  source text not null check (source in ('youtube', 'tiktok', 'pinterest', 'graph')),
  source_url text,                                              -- opened in SFSafariViewController, never embedded
  source_handle text,
  source_score numeric,                                         -- 12.0 = 12× its channel average
  title text not null,
  why text,                                                     -- one line; cites her recording (why_recording_id, why_ms)
  why_recording_id uuid references recordings(id) on delete set null,
  why_ms int,
  frame_url text,
  rank int not null,
  status text not null default 'shown' check (status in ('shown', 'pinned', 'dismissed', 'hidden', 'expired')),
  created_at timestamptz not null default now(),
  acted_at timestamptz
);
create index suggestions_thread_idx on suggestions (thread_id, status, rank);
create index suggestions_creator_idx on suggestions (creator_id, created_at desc);

-- The why line quotes her ("you said 'box tips over first' on Thu 0:31"). Deleting that recording must leave
-- nothing of it behind (0007), so the quote goes with it; the suggestion stays.
create function forget_suggestion_why() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  update suggestions set why = null, why_ms = null where why_recording_id = old.id;
  return old;
end;
$$;
create trigger recordings_forget_suggestion_why before delete on recordings
  for each row execute function forget_suggestion_why();

alter table suggestions enable row level security;
create policy "own suggestions: read" on suggestions for select using (creator_id = (auth.jwt() ->> 'sub'));

-- ── suggestion_signals ──────────────────────────────────────────────────────────────────────────────────────────
create table suggestion_signals (
  id bigserial primary key,
  creator_id text not null references creators(id) on delete cascade,
  suggestion_id uuid not null references suggestions(id) on delete cascade,
  signal text not null check (signal in ('pin', 'dismiss', 'hide', 'open', 'play_why')),
  created_at timestamptz not null default now()
);
create index suggestion_signals_suggestion_idx on suggestion_signals (suggestion_id, created_at);

alter table suggestion_signals enable row level security;
create policy "own suggestion signals: read" on suggestion_signals for select using (creator_id = (auth.jwt() ->> 'sub'));
-- 'open' and 'play_why' change nothing but the log, so she writes them directly — for her own suggestions only.
-- pin / dismiss / hide go through the functions that also change the suggestion's status.
create policy "own suggestion signals: open, play_why" on suggestion_signals for insert
  with check (
    creator_id = (auth.jwt() ->> 'sub')
    and signal in ('open', 'play_why')
    and exists (select 1 from suggestions s where s.id = suggestion_id and s.creator_id = (auth.jwt() ->> 'sub'))
  );

-- ── style_signals ───────────────────────────────────────────────────────────────────────────────────────────────
create table style_signals (
  id bigserial primary key,
  creator_id text not null references creators(id) on delete cascade,
  kind text not null,                 -- 'suggestion_pin' | 'suggestion_dismiss' | 'take_pick' (Job D) | …
  field text,                         -- a suggestion's field: format | sound | aesthetic | topic | graph
  source text,                        -- youtube | tiktok | pinterest | graph | …
  payload jsonb not null default '{}',
  created_at timestamptz not null default now()
);
create index style_signals_creator_idx on style_signals (creator_id, kind, created_at desc);

alter table style_signals enable row level security;
create policy "own style signals: read" on style_signals for select using (creator_id = (auth.jwt() ->> 'sub'));

-- The one writer. Called by the app as her (security invoker is not enough to insert — there's no insert policy —
-- so it's definer, and the creator is always the caller's own sub) and by other SQL functions (pin / dismiss).
-- payload.field and payload.source, when present, are lifted into their columns; the whole payload is kept.
create function write_style_signal(p_kind text, p_payload jsonb default '{}')
returns bigint
language plpgsql security definer set search_path = public as $$
declare
  me text := auth.jwt() ->> 'sub';
  new_id bigint;
begin
  if me is null then raise exception 'write_style_signal: no signed-in creator'; end if;
  if coalesce(trim(p_kind), '') = '' then raise exception 'write_style_signal: kind is required'; end if;
  insert into style_signals (creator_id, kind, field, source, payload)
  values (me, p_kind, p_payload ->> 'field', p_payload ->> 'source', coalesce(p_payload, '{}'))
  returning id into new_id;
  return new_id;
end;
$$;
revoke execute on function write_style_signal(text, jsonb) from public, anon;
grant execute on function write_style_signal(text, jsonb) to authenticated;

-- ── cards: a pinned suggestion is a card ────────────────────────────────────────────────────────────────────────
alter table cards drop constraint cards_source_check;
alter table cards add constraint cards_source_check
  check (source in ('voice', 'import', 'muse', 'youtube', 'tiktok', 'pinterest'));
alter table cards
  add column source_url text,
  add column source_suggestion_id uuid references suggestions(id) on delete set null;
-- A pinned card was never said, so it has no recording. Every card from her voice, an import or Muse still must.
-- (Keyed on source, not source_suggestion_id: that goes null if the suggestion is deleted, and the card stays.)
alter table cards alter column recording_id drop not null;
alter table cards add constraint cards_recording_unless_pinned
  check (recording_id is not null or source in ('youtube', 'tiktok', 'pinterest'));

create temp table r(n serial, check_name text, ok boolean, detail text) on commit drop;
grant all on r to authenticated; grant all on r_n_seq to authenticated;

-- Fixtures, as the service role: a recording, a project and a thread for "me", one suggestion each for me and other.
do $$
declare me text := 'user_3JfFAEHAdkvURqPjYDQ4BkVd2rb'; other text := 'user_3JfYR4D8eJVCL3yieXStYYoqwaH';
        rec uuid; proj uuid; th uuid; s_me uuid; s_other uuid;
begin
  insert into recordings (creator_id, source, storage_path) values (me, 'phone', 'test/0028') returning id into rec;
  insert into projects (creator_id, name) values (me, 'Launch video 0028') returning id into proj;
  insert into threads (creator_id, title, return_count, project_id) values (me, 'Rooftop chase 0028', 3, proj) returning id into th;
  insert into suggestions (creator_id, project_id, thread_id, field, source, title, why, why_recording_id, why_ms, rank)
    values (me, proj, th, 'format', 'youtube', 'Open on the box', 'you said "box tips over first" on Thu 0:31', rec, 31000, 1)
    returning id into s_me;
  insert into suggestions (creator_id, field, source, title, rank) values (other, 'sound', 'tiktok', 'Not hers', 1) returning id into s_other;
  perform set_config('t.rec', rec::text, true);
  perform set_config('t.me', s_me::text, true);
  perform set_config('t.other', s_other::text, true);

  insert into r (check_name, ok, detail)
    select 'RLS is on for the three new tables', count(*) = 3, string_agg(relname, ', ')
      from pg_class where relname in ('suggestions', 'suggestion_signals', 'style_signals') and relrowsecurity;

  -- cards.source widened; a pinned card may have no recording, a voice card may not.
  begin
    insert into cards (creator_id, title, gist, play_from_ms, confidence, source, source_url, source_suggestion_id)
      values (me, 'Open on the box', 'Open on the box', 0, 1, 'youtube', 'https://youtube.com/watch?v=x', s_me);
    insert into r (check_name, ok, detail) values ('a youtube card needs no recording', true, 'inserted');
  exception when others then
    insert into r (check_name, ok, detail) values ('a youtube card needs no recording', false, sqlerrm);
  end;
  begin
    insert into cards (creator_id, title, gist, play_from_ms, confidence, source) values (me, 'x', 'x', 0, 1, 'voice');
    insert into r (check_name, ok, detail) values ('a voice card still needs its recording', false, 'inserted');
  exception when check_violation then
    insert into r (check_name, ok, detail) values ('a voice card still needs its recording', true, sqlerrm);
  end;
  begin
    insert into cards (creator_id, recording_id, title, gist, play_from_ms, confidence, source) values (me, rec, 'x', 'x', 0, 1, 'myspace');
    insert into r (check_name, ok, detail) values ('an unknown source is refused', false, 'inserted');
  exception when check_violation then
    insert into r (check_name, ok, detail) values ('an unknown source is refused', true, sqlerrm);
  end;
  begin
    insert into cards (creator_id, recording_id, title, gist, play_from_ms, confidence, source) values (me, rec, 'x', 'x', 0, 1, 'muse');
    insert into r (check_name, ok, detail) values ('muse is a card source', true, 'inserted');
  exception when others then
    insert into r (check_name, ok, detail) values ('muse is a card source', false, sqlerrm);
  end;
end $$;

-- As her.
select set_config('request.jwt.claims', '{"sub":"user_3JfFAEHAdkvURqPjYDQ4BkVd2rb","role":"authenticated"}', true);
set local role authenticated;
do $$
declare n int; sid bigint; f text; src text;
begin
  select count(*) into n from suggestions;
  insert into r (check_name, ok, detail) values ('she sees her suggestions, not another creator''s', n = 1 and exists (select 1 from suggestions where id = current_setting('t.me')::uuid), n::text);

  begin
    update suggestions set status = 'pinned' where id = current_setting('t.me')::uuid;
    get diagnostics n = row_count;
    insert into r (check_name, ok, detail) values ('she can''t change a suggestion''s status directly', n = 0, n::text || ' updated');
  end;

  insert into suggestion_signals (creator_id, suggestion_id, signal) values ('user_3JfFAEHAdkvURqPjYDQ4BkVd2rb', current_setting('t.me')::uuid, 'open');
  insert into r (check_name, ok, detail) values ('she logs an open on her own suggestion', true, 'inserted');
  begin
    insert into suggestion_signals (creator_id, suggestion_id, signal) values ('user_3JfFAEHAdkvURqPjYDQ4BkVd2rb', current_setting('t.me')::uuid, 'pin');
    insert into r (check_name, ok, detail) values ('a pin can''t be logged without pinning', false, 'inserted');
  exception when insufficient_privilege then
    insert into r (check_name, ok, detail) values ('a pin can''t be logged without pinning', true, sqlerrm);
  end;
  begin
    insert into suggestion_signals (creator_id, suggestion_id, signal) values ('user_3JfFAEHAdkvURqPjYDQ4BkVd2rb', current_setting('t.other')::uuid, 'open');
    insert into r (check_name, ok, detail) values ('she can''t log on another creator''s suggestion', false, 'inserted');
  exception when insufficient_privilege then
    insert into r (check_name, ok, detail) values ('she can''t log on another creator''s suggestion', true, sqlerrm);
  end;

  sid := write_style_signal('suggestion_pin', '{"field":"format","source":"youtube","suggestion_id":"x"}');
  select field, source into f, src from style_signals where id = sid;
  insert into r (check_name, ok, detail) values ('write_style_signal writes hers, field and source lifted', f = 'format' and src = 'youtube', coalesce(f, '∅') || ' ' || coalesce(src, '∅'));
  begin
    insert into style_signals (creator_id, kind) values ('user_3JfFAEHAdkvURqPjYDQ4BkVd2rb', 'take_pick');
    insert into r (check_name, ok, detail) values ('style_signals are written only through write_style_signal', false, 'inserted');
  exception when insufficient_privilege then
    insert into r (check_name, ok, detail) values ('style_signals are written only through write_style_signal', true, sqlerrm);
  end;
end $$;
reset role;

-- Deleting the recording forgets the quote; the suggestion stays.
do $$
declare w text; still boolean;
begin
  delete from recordings where id = current_setting('t.rec')::uuid;
  select why, true into w, still from suggestions where id = current_setting('t.me')::uuid;
  insert into r (check_name, ok, detail) values ('deleting her recording removes the why that quotes it', still and w is null, coalesce(w, '∅'));
end $$;

select n, case when ok then 'pass' else 'FAIL' end as result, check_name, detail from r order by n;
rollback;
