-- Rolled-back test for 0027 (write, test in a rolled-back transaction, dry-run, push).
--
--   node scripts/build-sql-test.mjs 0027 && supabase db query --linked -f scripts/test-0027.sql

-- Generated by scripts/build-sql-test.mjs from test-0027.head.sql, 0027, test-0027.body.sql.
begin;
-- OAuth 2.1 for the Muse connector (Job F2): a reviewer's client — or any MCP client — connects to /mcp without a
-- pasted key. apps/web is the authorization server; Clerk is how she signs in to it. Ivy issues its own tokens so
-- they can carry Ivy's scopes (ideas:read, ideas:capture), which Clerk's OAuth apps can't, and so they show up and
-- revoke in Connect your Muse next to her keys.
--
--   oauth_clients         who may ask: registered (RFC 7591, /oauth/register) or identified by a client metadata
--                         document URL (CIMD, MCP 2026-07-28). Service role only.
--   oauth_authorizations  one authorization request: made at /oauth/authorize, decided on the consent page, and
--                         exchanged once for tokens at /oauth/token (PKCE S256). Service role only.
--   creator_api_keys      a grant is a key row with a client_id: its hash is the access token's, refresh_hash the
--                         refresh token's (rotated on every refresh), expires_at the access token's expiry. Revoking
--                         the row (Connect your Muse, or /oauth/revoke) ends both.

create table oauth_clients (
  client_id text primary key,                      -- random for registered clients; the https URL for CIMD
  kind text not null check (kind in ('registered', 'metadata_document')),
  client_name text not null check (length(client_name) between 1 and 120),
  client_uri text,
  redirect_uris text[] not null check (cardinality(redirect_uris) between 1 and 10),
  token_endpoint_auth_method text not null default 'none'
    check (token_endpoint_auth_method in ('none', 'client_secret_post', 'client_secret_basic')),
  secret_hash text,                                -- sha256, confidential registered clients only
  metadata jsonb not null default '{}',            -- what the client sent, for audit
  created_at timestamptz not null default now(),
  refreshed_at timestamptz not null default now(), -- CIMD: when the document was last fetched
  check ((token_endpoint_auth_method = 'none') = (secret_hash is null))
);
create index oauth_clients_created_idx on oauth_clients (created_at desc);
alter table oauth_clients enable row level security;

create table oauth_authorizations (
  id uuid primary key default gen_random_uuid(),   -- also the consent page's id: unguessable, bound to her
  creator_id text not null references creators(id) on delete cascade,
  client_id text not null references oauth_clients(client_id) on delete cascade,
  redirect_uri text not null,
  code_challenge text not null,                    -- S256 only
  requested_scopes text[] not null,
  granted_scopes text[],                           -- what she allowed; null until she decides
  state text,
  resource text,                                   -- RFC 8707, checked against /mcp
  code_hash text unique,                           -- sha256 of the code, set when she allows
  key_id uuid references creator_api_keys(id) on delete set null,  -- the grant the code was exchanged for
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,                 -- the request, then the code
  decided_at timestamptz,
  used_at timestamptz
);
create index oauth_authorizations_creator_idx on oauth_authorizations (creator_id, created_at desc);
alter table oauth_authorizations enable row level security;

alter table creator_api_keys
  add column client_id text references oauth_clients(client_id) on delete cascade,
  add column refresh_hash text unique,
  add column expires_at timestamptz;             -- null for a pasted key: it lasts until revoked

-- She sees which of her keys are sign-ins, from what, and until when; never the refresh hash (0024's grants).
grant select (client_id, expires_at) on creator_api_keys to authenticated;

create temp table r(n serial, check_name text, ok boolean, detail text) on commit drop;
grant all on r to authenticated; grant all on r_n_seq to authenticated;

do $$
declare me text := 'user_3JfFAEHAdkvURqPjYDQ4BkVd2rb'; k uuid; a uuid;
begin
  insert into oauth_clients (client_id, kind, client_name, redirect_uris) values ('ivc_test0027', 'registered', 'Test', array['http://127.0.0.1/cb']);
  begin
    insert into oauth_clients (client_id, kind, client_name, redirect_uris, token_endpoint_auth_method) values ('ivc_test0027b', 'registered', 'Test', array['https://x.example/cb'], 'client_secret_post');
    insert into r (check_name, ok, detail) values ('a confidential client needs a secret hash', false, 'inserted');
  exception when check_violation then
    insert into r (check_name, ok, detail) values ('a confidential client needs a secret hash', true, sqlerrm);
  end;
  insert into creator_api_keys (creator_id, hash, refresh_hash, scopes, label, client_id, expires_at)
    values (me, 'test-0027-at', 'test-0027-rt', array['ideas:read'], 'Test', 'ivc_test0027', now() + interval '30 days') returning id into k;
  insert into oauth_authorizations (creator_id, client_id, redirect_uri, code_challenge, requested_scopes, expires_at, key_id)
    values (me, 'ivc_test0027', 'http://127.0.0.1/cb', repeat('a', 43), array['ideas:read'], now() + interval '5 minutes', k) returning id into a;
  perform set_config('t.key', k::text, true);

  delete from creator_api_keys where id = k;
  insert into r (check_name, ok, detail)
    select 'an authorization outlives its grant (key_id set null)', key_id is null, coalesce(key_id::text, 'null') from oauth_authorizations where id = a;
  insert into creator_api_keys (creator_id, hash, refresh_hash, scopes, label, client_id, expires_at)
    values (me, 'test-0027-at2', 'test-0027-rt2', array['ideas:read'], 'Test', 'ivc_test0027', now() + interval '30 days') returning id into k;
  perform set_config('t.key', k::text, true);
end $$;

select set_config('request.jwt.claims', '{"sub":"user_3JfFAEHAdkvURqPjYDQ4BkVd2rb","role":"authenticated"}', true);
set local role authenticated;
do $$
declare n int; c text;
begin
  select client_id into c from creator_api_keys where id = current_setting('t.key')::uuid;
  insert into r (check_name, ok, detail) values ('she sees which app a grant is for', c = 'ivc_test0027', coalesce(c, 'null'));
  begin
    perform refresh_hash from creator_api_keys where id = current_setting('t.key')::uuid;
    insert into r (check_name, ok, detail) values ('she can''t read the refresh hash', false, 'read');
  exception when insufficient_privilege then
    insert into r (check_name, ok, detail) values ('she can''t read the refresh hash', true, sqlerrm);
  end;
  select count(*) into n from oauth_clients;
  insert into r (check_name, ok, detail) values ('she can''t read oauth_clients', n = 0, n::text);
  select count(*) into n from oauth_authorizations;
  insert into r (check_name, ok, detail) values ('she can''t read oauth_authorizations', n = 0, n::text);
  update creator_api_keys set revoked_at = now() where id = current_setting('t.key')::uuid;
  get diagnostics n = row_count;
  insert into r (check_name, ok, detail) values ('she revokes a sign-in like a key', n = 1, n::text);
end $$;
reset role;

delete from oauth_clients where client_id = 'ivc_test0027';
insert into r (check_name, ok, detail)
  select 'a deleted client takes its grants', count(*) = 0, count(*)::text from creator_api_keys where client_id = 'ivc_test0027';

select n, case when ok then 'pass' else 'FAIL' end as result, check_name, detail from r order by n;
rollback;
