-- Rolled-back test for 0033 (write, test in a rolled-back transaction, dry-run, push). Job B revised: card shapes.
--
--   node scripts/build-sql-test.mjs 0033 && supabase db query --linked -f scripts/test-0033.sql

-- Generated by scripts/build-sql-test.mjs from test-0033.head.sql, 0033, test-0033.body.sql.
begin;
-- Job B revised — ideas have shapes (Figma 227:5, v3.4 "Creator-first"). Rule 6 becomes "every card gets the right
-- form": Home shows the form each idea needs instead of a generated frame on everything.
--
--   shape         photo | quote | diagram | board | text — classify_v7 picks it; null on cards made before v7
--                 (the app renders those as before: the frame if there is one, else a text card)
--   shape_set_by  'ivy' (the classifier, or the pipeline's fallback when a photo search finds nothing) | 'creator'
--                 (she chose it with Change view; the pipeline never overrides that)
--   visual_query  2–6 plain words for the Unsplash search (photo)
--   quote         {text, speaker}       — text verbatim from the segment; speaker null = her own voice
--   diagram       {title, rows:[{from, to}]}
--   board         {hook, beats:[…]}      — the status pill is the thread's stage, read at render time
--   frame_attribution  {provider:'unsplash', photo_id, photographer, photographer_url, photo_url, download_location}
--                 — credited on the tile and the idea page (Unsplash API guidelines); frame_url hotlinks the photo.
--
-- Job G.1's brief numbered its card_frames table 0033; that table isn't in this job and takes the next number.

alter table cards
  add column shape text check (shape in ('photo', 'quote', 'diagram', 'board', 'text')),
  add column shape_set_by text check (shape_set_by in ('ivy', 'creator')),
  add column visual_query text,
  add column quote jsonb,
  add column diagram jsonb,
  add column board jsonb,
  add column frame_attribution jsonb;

-- A shape needs its payload; the pipeline's invariants already guarantee it, this keeps the app's writes honest too.
alter table cards add constraint cards_shape_has_payload check (
  shape is null
  or shape = 'text'
  or (shape = 'photo')
  or (shape = 'quote' and quote is not null)
  or (shape = 'diagram' and diagram is not null)
  or (shape = 'board' and board is not null)
);

create temp table r(n serial, check_name text, ok boolean, detail text) on commit drop;
grant all on r to authenticated; grant all on r_n_seq to authenticated;

do $$
declare me text := 'user_3JfFAEHAdkvURqPjYDQ4BkVd2rb'; rec uuid; c uuid;
begin
  insert into recordings (creator_id, source, storage_path) values (me, 'phone', 'test/0033') returning id into rec;
  insert into cards (creator_id, recording_id, title, gist, play_from_ms, confidence, shape, shape_set_by, quote)
    values (me, rec, 'We scaled the apology', 'x', 760000, 0.9, 'quote', 'ivy', '{"text":"We scaled the apology.","speaker":null}')
    returning id into c;
  perform set_config('t.c', c::text, true);
  insert into r values (default, 'a quote card with its quote is accepted', true, c::text);

  begin
    insert into cards (creator_id, recording_id, title, gist, play_from_ms, confidence, shape) values (me, rec, 'x', 'x', 0, 0.9, 'diagram');
    insert into r values (default, 'a diagram card needs its diagram', false, 'inserted');
  exception when check_violation then
    insert into r values (default, 'a diagram card needs its diagram', true, sqlerrm);
  end;
  begin
    insert into cards (creator_id, recording_id, title, gist, play_from_ms, confidence, shape) values (me, rec, 'x', 'x', 0, 0.9, 'sticker');
    insert into r values (default, 'an unknown shape is refused', false, 'inserted');
  exception when check_violation then
    insert into r values (default, 'an unknown shape is refused', true, sqlerrm);
  end;
  insert into cards (creator_id, recording_id, title, gist, play_from_ms, confidence) values (me, rec, 'old', 'x', 0, 0.9) returning id into c;
  insert into r values (default, 'a card with no shape (made before 0033) is still accepted', (select shape is null from cards where id = c), c::text);
end $$;

-- As her: Change view writes the shape and the signal (lib/idea.ts setShape).
select set_config('request.jwt.claims', '{"sub":"user_3JfFAEHAdkvURqPjYDQ4BkVd2rb","role":"authenticated"}', true);
set local role authenticated;
do $$
declare n int; s text; by_ text;
begin
  update cards set shape = 'text', shape_set_by = 'creator' where id = current_setting('t.c')::uuid;
  get diagnostics n = row_count;
  select shape, shape_set_by into s, by_ from cards where id = current_setting('t.c')::uuid;
  insert into r values (default, 'she can change her card''s view', n = 1 and s = 'text' and by_ = 'creator', format('%s rows, %s by %s', n, s, by_));
  begin
    update cards set shape = 'board' where id = current_setting('t.c')::uuid;
    insert into r values (default, 'she can''t pick a view the card has no words for', false, 'updated');
  exception when check_violation then
    insert into r values (default, 'she can''t pick a view the card has no words for', true, sqlerrm);
  end;
  perform write_style_signal('shape_change', jsonb_build_object('field', 'shape', 'card_id', current_setting('t.c'), 'from', 'quote', 'to', 'text'));
  select count(*) into n from style_signals where kind = 'shape_change' and payload ->> 'card_id' = current_setting('t.c');
  insert into r values (default, 'Change view is a style signal', n = 1, format('%s signal(s)', n));
end $$;
reset role;

select n, case when ok then 'pass' else 'FAIL' end as result, check_name, detail from r order by n;
rollback;
